kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cpx
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "ingresses", "pods", "secrets", "routes", "routes/status", "nodes", "namespaces"]
    verbs: ["*"]
  - apiGroups: ["extensions"]
    resources: ["ingresses", "ingresses/status"]
    verbs: ["*"]
  - apiGroups: ["citrix.com"]
    resources: ["rewritepolicies", "vips"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cpx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cpx
subjects:
- kind: ServiceAccount
  name: cpx
  namespace: default
apiVersion: rbac.authorization.k8s.io/v1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cpx
  namespace: default
---
apiVersion: v1
kind: Pod
metadata:
 name: lb-service-cic
 labels:
   app: lb-service-cic
spec:
     serviceAccountName: cpx
     containers:
     - name: lb-service-cic
       image: "quay.io/citrix/citrix-k8s-ingress-controller:1.2.0"
       env:
        # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
        - name: "NS_IP"
          value: "192.168.10.50"
        # Set username for Nitro
        # Set log level
        - name: "NS_ENABLE_MONITORING"
          value: "NO"
        - name: "NS_USER"
          value: "nsroot"
        - name: "NS_PASSWORD"
          value: "nsroot"
        - name: "EULA"
          value: "yes"
        - name: "LOGLEVEL"
          value: "DEBUG"
#        - name: "NS_VIP"
#          value: "10.217.101.183"
        - name: "NS_APPS_NAME_PREFIX"
          value: "HW-"
       args:
         - --ingress-classes
           vpx
         - --feature-node-watch
           false
         - --ipam
           citrix-ipam-controller 
       imagePullPolicy: IfNotPresent
